{% set name = "flask-sspi" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-SSPI-{{ version }}.tar.gz
  sha256: b183ff42ad26c1334855707b8861d3a0292f99959be5d0a67b98fd3a1043e0c7

build:
  skip: true  # [not win or py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - flask
    - mock
    - python
    - pywin32

test:
  imports:
    - flask_sspi
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ceprio/flask-sspi
  summary: SSPI authentication support for Flask
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fuglede
