{% set name = "flask-sspi" %}
{% set version = "0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6d43c6ec2384846fbd994755237f420ab499ed912e2272fecbd5f875c7789965

build:
  skip: true  # [not win or py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - flask
    - mock
    - python
    - pywin32

test:
  imports:
    - flask_sspi
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ceprio/flask-sspi
  summary: SSPI authentication support for Flask
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fuglede
