{% set name = "flask-sspi" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-SSPI-{{ version }}.tar.gz
  sha256: 6d90f06603939204ee587007ac677aa06769e2d0aceb1509c875a5ac5ce05924

build:
  skip: true  # [not win or py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - flask
    - mock
    - python
    - pywin32

test:
  imports:
    - flask_sspi
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ceprio/flask-sspi
  summary: SSPI authentication support for Flask
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fuglede
